# .streamlit/config.toml

[theme]
base="light"  # Use "light" for a light theme

primaryColor = '#FF8C02' # Bright Orange

backgroundColor = '#00325B' # Dark Blue

secondaryBackgroundColor = '#55B2FF' # Lighter Blue
textColor="#000000"  # Black text color for contrast
font="sans serif"  # Use sans-serif font
