# .streamlit/config.toml

[theme]
base="light"  # Use "light" for a light theme
primaryColor="#00BFFF"  # Light blue color for primary elements
backgroundColor="#FFFFFF"  # White background color
secondaryBackgroundColor="#F0F8FF"  # Light blue background for sidebars
textColor="#000000"  # Black text color for contrast
font="sans serif"  # Use sans-serif font
